# Complete Gen 2 Item Table mapped directly by ROM Hex Byte (0x01 to 0xFF) -> ITEM_nnn (Decimal)

items_by_hex_byte = {
    0x01: ("MASTER_BALL", "Master Ball"),
    0x02: ("ULTRA_BALL", "Ultra Ball"),
    0x03: ("BRIGHTPOWDER", "BrightPowder"),
    0x04: ("GREAT_BALL", "Great Ball"),
    (0x05): ("POKE_BALL", "Poké Ball"),
    0x06: ("TOWN_MAP", "Town Map"),
    0x07: ("BICYCLE", "Bicycle"),
    0x08: ("MOON_STONE", "Moon Stone"),
    0x09: ("ANTIDOTE", "Antidote"),
    0x0A: ("BURN_HEAL", "Burn Heal"),
    0x0B: ("ICE_HEAL", "Ice Heal"),
    0x0C: ("AWAKENING", "Awakening"),
    0x0D: ("PARLYZ_HEAL", "Parlyz Heal"),
    0x0E: ("FULL_RESTORE", "Full Restore"),
    0x0F: ("MAX_POTION", "Max Potion"),
    0x10: ("HYPER_POTION", "Hyper Potion"),
    0x11: ("SUPER_POTION", "Super Potion"),
    0x12: ("POTION", "Potion"),
    0x13: ("ESCAPE_ROPE", "Escape Rope"),
    0x14: ("REPEL", "Repel"),                  # ITEM_020
    0x15: ("MAX_ELIXER", "Max Elixir"),
    0x16: ("FIRE_STONE", "Fire Stone"),        # ITEM_022
    0x17: ("THUNDERSTONE", "Thunderstone"),
    0x18: ("WATER_STONE", "Water Stone"),
    0x19: ("ITEM_19", "Unused Item 19"),
    0x1A: ("HP_UP", "HP Up"),
    0x1B: ("PROTEIN", "Protein"),
    0x1C: ("IRON", "Iron"),
    0x1D: ("CARBOS", "Carbos"),                # ITEM_029
    0x1E: ("LUCKY_PUNCH", "Lucky Punch"),
    0x1F: ("CALCIUM", "Calcium"),
    0x20: ("RARE_CANDY", "Rare Candy"),
    0x21: ("X_ACCURACY", "X Accuracy"),
    0x22: ("LEAF_STONE", "Leaf Stone"),
    0x23: ("METAL_POWDER", "Metal Powder"),
    0x24: ("NUGGET", "Nugget"),
    0x25: ("PP_UP_GEN1", "PP Up (Gen 1 constant)"),
    0x26: ("POKEDOLL", "Poké Doll"),
    0x27: ("FULL_HEAL", "Full Heal"),
    0x28: ("REVIVE", "Revive"),
    0x29: ("MAX_REVIVE", "Max Revive"),
    0x2A: ("GUARD_SPEC", "Guard Spec."),
    0x2B: ("SUPER_REPEL", "Super Repel"),
    0x2C: ("MAX_REPEL", "Max Repel"),
    0x2D: ("DIRE_HIT", "Dire Hit"),
    0x2E: ("ITEM_2E", "Unused Item 2E"),
    0x2F: ("FRESH_WATER", "Fresh Water"),
    0x30: ("SODA_POP", "Soda Pop"),
    0x31: ("LEMONADE", "Lemonade"),
    0x32: ("X_ATTACK", "X Attack"),
    0x33: ("ITEM_33", "Unused Item 33"),
    0x34: ("X_DEFEND", "X Defend"),
    0x35: ("X_SPEED", "X Speed"),
    0x36: ("X_SPECIAL", "X Special"),
    0x37: ("COIN_CASE", "Coin Case"),
    0x38: ("ITEMFINDER", "Itemfinder"),
    0x39: ("POKEFLUTE", "Poké Flute"),
    0x3A: ("EXP_SHARE", "Exp. Share"),
    0x3B: ("OLD_ROD", "Old Rod"),
    0x3C: ("SILVER_LEAF", "Silver Leaf"),      # ITEM_060
    0x3D: ("SUPER_ROD", "Super Rod"),
    0x3E: ("PP_UP", "PP Up"),                  # ITEM_062
    0x3F: ("ETHER", "Ether"),
    0x40: ("MAX_ETHER", "Max Ether"),
    0x41: ("ELIXER", "Elixir"),
    0x42: ("RED_SCALE", "Red Scale"),
    0x43: ("SECRETPOTION", "SecretPotion"),
    0x44: ("S_S_TICKET", "S.S. Ticket"),
    0x45: ("MYSTERY_EGG", "Mystery Egg"),
    0x46: ("CLEAR_BELL", "Clear Bell"),
    0x47: ("SILVER_WING", "Silver Wing"),
    0x48: ("MOOMOO_MILK", "Moomoo Milk"),
    0x49: ("QUICK_CLAW", "Quick Claw"),
    0x4A: ("PSNCUREBERRY", "Psncureberry"),
    0x4B: ("SOFT_SAND", "Soft Sand"),
    0x4C: ("SHARP_BEAK", "Sharp Beak"),
    0x4D: ("PRZCUREBERRY", "Przcureberry"),
    0x4E: ("BURNT_BERRY_GS", "Burnt Berry (GS constant)"),
    0x4F: ("ICE_BERRY", "Ice Berry"),
    0x50: ("POISON_BARB", "Poison Barb"),
    0x51: ("KING_ROCK", "King's Rock"),
    0x52: ("BITTER_BERRY", "Bitter Berry"),
    0x53: ("MINT_BERRY", "Mint Berry"),
    0x54: ("RED_APRICORN", "Red Apricorn"),
    0x55: ("TINYMUSHROOM", "TinyMushroom"),
    0x56: ("BIG_MUSHROOM", "Big Mushroom"),
    0x57: ("SILVERPOWDER", "SilverPowder"),
    0x58: ("BLU_APRICORN", "Blu Apricorn"),
    0x59: ("AMULET_COIN", "Amulet Coin"),
    0x5A: ("YLW_APRICORN", "Ylw Apricorn"),
    0x5B: ("GRN_APRICORN", "Grn Apricorn"),
    0x5C: ("CLEANSE_TAG", "Cleanse Tag"),
    0x5D: ("MYSTIC_WATER", "Mystic Water"),
    0x5E: ("TWISTEDSPOON", "TwistedSpoon"),
    0x5F: ("WHT_APRICORN", "Wht Apricorn"),
    0x60: ("BLACKBELT_I", "Black Belt"),
    0x61: ("BLK_APRICORN", "Blk Apricorn"),
    0x62: ("PNK_APRICORN", "Pnk Apricorn"),
    0x63: ("BLACK_GLASSES", "Black Glasses"),
    0x64: ("SLOWPOKETAIL", "SlowpokeTail"),
    0x65: ("PINK_BOW", "Pink Bow"),
    0x66: ("STICK", "Stick"),
    0x67: ("SMOKE_BALL", "Smoke Ball"),
    0x68: ("NEVERMELTICE", "NeverMeltIce"),    # ITEM_104
    0x69: ("MAGNET", "Magnet"),
    0x6A: ("MIRACLEBERRY", "Miracleberry"),
    0x6B: ("BURNT_BERRY", "Burnt Berry"),      # ITEM_107
    0x6C: ("PEARL", "Pearl"),
    0x6D: ("BIG_PEARL", "Big Pearl"),
    0x6E: ("EVERSTONE", "Everstone"),
    0x6F: ("SPELL_TAG", "Spell Tag"),
    0x70: ("RAGECANDYBAR", "RageCandyBar"),
    0x71: ("GS_BALL", "GS Ball"),
    0x72: ("BLUE_CARD", "Blue Card"),
    0x73: ("MIRACLE_SEED", "Miracle Seed"),
    0x74: ("THICK_CLUB", "Thick Club"),
    0x75: ("FOCUS_BAND", "Focus Band"),
    0x76: ("ITEM_76", "Unused Item 76"),
    0x77: ("ENERGYPOWDER", "EnergyPowder"),
    0x78: ("ENERGY_ROOT", "Energy Root"),
    0x79: ("HEAL_POWDER", "Heal Powder"),
    0x7A: ("REVIVAL_HERB", "Revival Herb"),
    0x7B: ("HARD_STONE", "Hard Stone"),
    0x7C: ("LUCKY_EGG", "Lucky Egg"),
    0x7D: ("CARD_KEY", "Card Key"),
    0x7E: ("MACHINE_PART", "Machine Part"),
    0x7F: ("EGG_TICKET", "Egg Ticket"),
    0x80: ("LOST_ITEM", "Lost Item"),
    0x81: ("STARDUST", "Stardust"),
    0x82: ("STAR_PIECE", "Star Piece"),
    0x83: ("BASEMENT_KEY", "Basement Key"),
    0x84: ("PASS", "Pass"),
    0x85: ("ITEM_85", "Unused Item 85"),
    0x86: ("ITEM_86", "Unused Item 86"),
    0x87: ("ITEM_87", "Unused Item 87"),
    0x88: ("CHARCOAL", "Charcoal"),
    0x89: ("BERRY_JUICE", "Berry Juice"),
    0x8A: ("SCOPE_LENS", "Scope Lens"),
    0x8B: ("ITEM_8B", "Unused Item 8B"),
    0x8C: ("ITEM_8C", "Unused Item 8C"),
    0x8D: ("METAL_COAT", "Metal Coat"),
    0x8E: ("DRAGON_FANG", "Dragon Fang"),
    0x8F: ("ITEM_8F", "Unused Item 8F"),
    0x90: ("LEFTOVERS", "Leftovers"),
    0x91: ("ITEM_91", "Unused Item 91"),
    0x92: ("ITEM_92", "Unused Item 92"),
    0x93: ("ITEM_93", "Unused Item 93"),
    0x94: ("MYSTERYBERRY", "Mysteryberry"),
    0x95: ("DRAGON_SCALE", "Dragon Scale"),
    0x96: ("BERSERK_GENE", "Berserk Gene"),
    0x97: ("ITEM_97", "Unused Item 97"),
    0x98: ("ITEM_98", "Unused Item 98"),
    0x99: ("ITEM_99", "Unused Item 99"),
    0x9A: ("SACRED_ASH", "Sacred Ash"),
    0x9B: ("HEAVY_BALL", "Heavy Ball"),
    0x9C: ("FLOWER_MAIL", "Flower Mail"),
    0x9D: ("LEVEL_BALL", "Level Ball"),
    (0x9E): ("LURE_BALL", "Lure Ball"),
    (0x9F): ("FAST_BALL", "Fast Ball"),
    (0xA0): ("ITEM_A0", "Unused Item A0"),
    (0xA1): ("LIGHT_BALL", "Light Ball"),
    (0xA2): ("FRIEND_BALL", "Friend Ball"),
    (0xA3): ("MOON_BALL", "Moon Ball"),
    (0xA4): ("LOVE_BALL", "Love Ball"),
    (0xA5): ("NORMAL_BOX", "Normal Box"),
    (0xA6): ("GORGEOUS_BOX", "Gorgeous Box"),
    (0xA7): ("SUN_STONE", "Sun Stone"),
    (0xA8): ("POLKADOT_BOW", "Polkadot Bow"),
    (0xA9): ("ITEM_A9", "Unused Item A9"),
    (0xAA): ("UP_GRADE", "Up-Grade"),
    (0xAB): ("BERRY", "Berry"),
    (0xAC): ("GOLD_BERRY", "Gold Berry"),
    (0xAD): ("SQUIRTBOTTLE", "SquirtBottle"),
    (0xAE): ("ITEM_AE", "Unused Item AE"),
    (0xAF): ("PARK_BALL", "Park Ball"),
    (0xB0): ("RAINBOW_WING", "Rainbow Wing"),
    (0xB1): ("ITEM_B1", "Unused Item B1"),
    (0xB2): ("BRICK_PIECE", "Brick Piece"),
    (0xB3): ("SURF_MAIL", "Surf Mail"),
    (0xB4): ("LITEBLUEMAIL", "Liteblue Mail"),
    (0xB5): ("PORTRAITMAIL", "Portrait Mail"),
    (0xB6): ("LOVELY_MAIL", "Lovely Mail"),
    (0xB7): ("EON_MAIL", "Eon Mail"),
    (0xB8): ("MORPH_MAIL", "Morph Mail"),
    (0xB9): ("BLUESKY_MAIL", "Bluesky Mail"),
    (0xBA): ("MUSIC_MAIL", "Music Mail"),
    (0xBB): ("MIRAGE_MAIL", "Mirage Mail"),
}

code_lines = [
    '#!/usr/bin/env python3',
    '"""',
    'General Item Finder Tool for Gen 2 Recomped (Silver, Gold, Crystal).',
    'Deducted directly from Gen 2 Hex Byte values and in-game clues.',
    '"""',
    '',
    'import sys',
    '',
    'GEN2_RECOMP_ITEMS = ['
]

for hex_val in range(1, 250):
    dec = hex_val
    if hex_val in items_by_hex_byte:
        key, name = items_by_hex_byte[hex_val]
    else:
        key, name = f"ITEM_{hex_val:02X}", f"Item {hex_val:03d}"
    code_lines.append(f'    ({dec}, 0x{hex_val:02X}, "{key}", "{name}"),')

code_lines.extend([
    ']',
    '',
    'def search_item(query):',
    '    query = query.strip()',
    '    if not query:',
    '        return',
    '',
    '    cleaned = query.upper().replace("ITEM_", "")',
    '    matches = []',
    '    val = None',
    '    if query.startswith("0x") or query.startswith("0X"):',
    '        try:',
    '            val = int(query, 16)',
    '        except ValueError:',
    '            pass',
    '    elif cleaned.isdigit():',
    '        try:',
    '            val = int(cleaned, 10)',
    '        except ValueError:',
    '            pass',
    '',
    '    hex_val_direct = None',
    '    if len(query.strip()) == 2:',
    '        try:',
    '            hex_val_direct = int(query.strip(), 16)',
    '        except ValueError:',
    '            pass',
    '',
    '    for dec, hex_val, key, name in GEN2_RECOMP_ITEMS:',
    '        if (val is not None and (dec == val or hex_val == val)) or \\',
    '           (hex_val_direct is not None and hex_val == hex_val_direct):',
    '            matches.append((dec, hex_val, key, name))',
    '            continue',
    '            ',
    '        if query.lower() in name.lower() or query.upper() in key.upper():',
    '            matches.append((dec, hex_val, key, name))',
    '',
    '    if not matches:',
    '        print(f"❌ No matching item found for query: \'{query}\'")',
    '        return',
    '',
    '    print(f"\\nFound {len(matches)} matching item(s):\\n")',
    '    print(f"{\'Recomp ID\':<12} | {\'Hex Byte\':<10} | {\'Item Name\'}")',
    '    print("-" * 48)',
    '    for dec, hex_val, key, name in matches:',
    '        print(f"ITEM_{dec:03d}     | 0x{hex_val:02X} (Hex) | {name}")',
    '    print()',
    '',
    'def main():',
    '    if len(sys.argv) > 1:',
    '        query = " ".join(sys.argv[1:])',
    '        search_item(query)',
    '    else:',
    '        print("=== Gen 2 Recomp Item Finder ===")',
    '        print("Type an item name (e.g. \'nevermeltice\'), Hex byte (e.g. \'0x68\'), or Recomp ID (e.g. \'104\').")',
    '        print("Type \'exit\' or \'q\' to quit.\\n")',
    '        while True:',
    '            try:',
    '                user_input = input("Search item > ")',
    '                if user_input.strip().lower() in ("exit", "quit", "q"):',
    '                    break',
    '                search_item(user_input)',
    '            except (KeyboardInterrupt, EOFError):',
    '                print("\\nGoodbye!")',
    '                break',
    '',
    'if __name__ == "__main__":',
    '    main()',
])

with open("item_finder.py", "w", encoding="utf-8") as f:
    f.write("\n".join(code_lines))

print("Updated item_finder.py with Gen 2 Hex -> ITEM_nnn mapping!")
