# Unbiased pokesilver / pokegold item table (ITEM_001 to ITEM_249)

pokesilver_items = [
    (1, 0x01, "MASTER_BALL", "Master Ball"),
    (2, 0x02, "ULTRA_BALL", "Ultra Ball"),
    (3, 0x03, "BRIGHTPOWDER", "BrightPowder"),
    (4, 0x04, "GREAT_BALL", "Great Ball"),
    (5, 0x05, "POKE_BALL", "Poké Ball"),
    (6, 0x06, "TOWN_MAP", "Town Map"),
    (7, 0x07, "BICYCLE", "Bicycle"),
    (8, 0x08, "MOON_STONE", "Moon Stone"),
    (9, 0x09, "ANTIDOTE", "Antidote"),
    (10, 0x0A, "BURN_HEAL", "Burn Heal"),
    (11, 0x0B, "ICE_HEAL", "Ice Heal"),
    (12, 0x0C, "AWAKENING", "Awakening"),
    (13, 0x0D, "PARLYZ_HEAL", "Parlyz Heal"),
    (14, 0x0E, "FULL_RESTORE", "Full Restore"),
    (15, 0x0F, "MAX_POTION", "Max Potion"),
    (16, 0x10, "HYPER_POTION", "Hyper Potion"),
    (17, 0x11, "SUPER_POTION", "Super Potion"),
    (18, 0x12, "POTION", "Potion"),
    (19, 0x13, "ESCAPE_ROPE", "Escape Rope"),
    (20, 0x14, "REPEL", "Repel"),
    (21, 0x15, "MAX_ELIXER", "Max Elixir"),
    (22, 0x16, "FIRE_STONE", "Fire Stone"),
    (23, 0x17, "THUNDERSTONE", "Thunderstone"),
    (24, 0x18, "WATER_STONE", "Water Stone"),
    (25, 0x19, "ITEM_19", "Unused Item 19"),
    (26, 0x1A, "HP_UP", "HP Up"),
    (27, 0x1B, "PROTEIN", "Protein"),
    (28, 0x1C, "IRON", "Iron"),
    (29, 0x1D, "CARBOS", "Carbos"),
    (30, 0x1E, "LUCKY_PUNCH", "Lucky Punch"),
    (31, 0x1F, "CALCIUM", "Calcium"),
    (32, 0x20, "RARE_CANDY", "Rare Candy"),
    (33, 0x21, "X_ACCURACY", "X Accuracy"),
    (34, 0x22, "LEAF_STONE", "Leaf Stone"),
    (35, 0x23, "METAL_POWDER", "Metal Powder"),
    (36, 0x24, "NUGGET", "Nugget"),
    (37, 0x25, "PP_UP_GEN1", "PP Up (Gen 1 constant)"),
    (38, 0x26, "POKEDOLL", "Poké Doll"),
    (39, 0x27, "FULL_HEAL", "Full Heal"),
    (40, 0x28, "REVIVE", "Revive"),
    (41, 0x29, "MAX_REVIVE", "Max Revive"),
    (42, 0x2A, "GUARD_SPEC", "Guard Spec."),
    (43, 0x2B, "SUPER_REPEL", "Super Repel"),
    (44, 0x2C, "MAX_REPEL", "Max Repel"),
    (45, 0x2D, "DIRE_HIT", "Dire Hit"),
    (46, 0x2E, "ITEM_2E", "Unused Item 2E"),
    (47, 0x2F, "FRESH_WATER", "Fresh Water"),
    (48, 0x30, "SODA_POP", "Soda Pop"),
    (49, 0x31, "LEMONADE", "Lemonade"),
    (50, 0x32, "X_ATTACK", "X Attack"),
    (51, 0x33, "ITEM_33", "Unused Item 33"),
    (52, 0x34, "X_DEFEND", "X Defend"),
    (53, 0x35, "X_SPEED", "X Speed"),
    (54, 0x36, "X_SPECIAL", "X Special"),
    (55, 0x37, "COIN_CASE", "Coin Case"),
    (56, 0x38, "ITEMFINDER", "Itemfinder"),
    (57, 0x39, "POKEFLUTE", "Poké Flute"),
    (58, 0x3A, "EXP_SHARE", "Exp. Share"),
    (59, 0x3B, "OLD_ROD", "Old Rod"),
    (60, 0x3C, "GOOD_ROD", "Good Rod"),
    (61, 0x3D, "SILVER_LEAF", "Silver Leaf"),
    (62, 0x3E, "SUPER_ROD", "Super Rod"),
    (63, 0x3F, "PP_UP", "PP Up"),
    (64, 0x40, "ETHER", "Ether"),
    (65, 0x41, "MAX_ETHER", "Max Ether"),
    (66, 0x42, "ELIXER", "Elixir"),
    (67, 0x43, "RED_SCALE", "Red Scale"),
    (68, 0x44, "SECRETPOTION", "SecretPotion"),
    (69, 0x45, "S_S_TICKET", "S.S. Ticket"),
    (70, 0x46, "MYSTERY_EGG", "Mystery Egg"),
    (71, 0x47, "CLEAR_BELL", "Clear Bell"),
    (72, 0x48, "SILVER_WING", "Silver Wing"),
    (73, 0x49, "MOOMOO_MILK", "Moomoo Milk"),
    (74, 0x4A, "QUICK_CLAW", "Quick Claw"),
    (75, 0x4B, "PSNCUREBERRY", "Psncureberry"),
    (76, 0x4C, "SOFT_SAND", "Soft Sand"),
    (77, 0x4D, "SHARP_BEAK", "Sharp Beak"),
    (78, 0x4E, "PRZCUREBERRY", "Przcureberry"),
    (79, 0x4F, "BURNT_BERRY", "Burnt Berry"),
    (80, 0x50, "ICE_BERRY", "Ice Berry"),
    (81, 0x51, "POISON_BARB", "Poison Barb"),
    (82, 0x52, "KING_ROCK", "King's Rock"),
    (83, 0x53, "BITTER_BERRY", "Bitter Berry"),
    (84, 0x54, "MINT_BERRY", "Mint Berry"),
    (85, 0x55, "RED_APRICORN", "Red Apricorn"),
    (86, 0x56, "TINYMUSHROOM", "TinyMushroom"),
    (87, 0x57, "BIG_MUSHROOM", "Big Mushroom"),
    (88, 0x58, "SILVERPOWDER", "SilverPowder"),
    (89, 0x59, "BLU_APRICORN", "Blu Apricorn"),
    (90, 0x5A, "AMULET_COIN", "Amulet Coin"),
    (91, 0x5B, "YLW_APRICORN", "Ylw Apricorn"),
    (92, 0x5C, "GRN_APRICORN", "Grn Apricorn"),
    (93, 0x5D, "CLEANSE_TAG", "Cleanse Tag"),
    (94, 0x5E, "MYSTIC_WATER", "Mystic Water"),
    (95, 0x5F, "TWISTEDSPOON", "TwistedSpoon"),
    (96, 0x60, "WHT_APRICORN", "Wht Apricorn"),
    (97, 0x61, "BLACKBELT_I", "Black Belt"),
    (98, 0x62, "BLK_APRICORN", "Blk Apricorn"),
    (99, 0x63, "PNK_APRICORN", "Pnk Apricorn"),
    (100, 0x64, "BLACK_GLASSES", "Black Glasses"),
    (101, 0x65, "SLOWPOKETAIL", "SlowpokeTail"),
    (102, 0x66, "PINK_BOW", "Pink Bow"),
    (103, 0x67, "STICK", "Stick"),
    (104, 0x68, "SMOKE_BALL", "Smoke Ball"),
    (105, 0x69, "NEVERMELTICE", "NeverMeltIce"),
    (106, 0x6A, "MAGNET", "Magnet"),
    (107, 0x6B, "MIRACLEBERRY", "Miracleberry"),
    (108, 0x6C, "PEARL", "Pearl"),
    (109, 0x6D, "BIG_PEARL", "Big Pearl"),
    (110, 0x6E, "EVERSTONE", "Everstone"),
    (111, 0x6F, "SPELL_TAG", "Spell Tag"),
    (112, 0x70, "RAGECANDYBAR", "RageCandyBar"),
    (113, 0x71, "GS_BALL", "GS Ball"),
    (114, 0x72, "BLUE_CARD", "Blue Card"),
    (115, 0x73, "MIRACLE_SEED", "Miracle Seed"),
    (116, 0x74, "THICK_CLUB", "Thick Club"),
    (117, 0x75, "FOCUS_BAND", "Focus Band"),
    (118, 0x76, "ITEM_76", "Unused Item 76"),
    (119, 0x77, "ENERGYPOWDER", "EnergyPowder"),
    (120, 0x78, "ENERGY_ROOT", "Energy Root"),
    (121, 0x79, "HEAL_POWDER", "Heal Powder"),
    (122, 0x7A, "REVIVAL_HERB", "Revival Herb"),
    (123, 0x7B, "HARD_STONE", "Hard Stone"),
    (124, 0x7C, "LUCKY_EGG", "Lucky Egg"),
    (125, 0x7D, "CARD_KEY", "Card Key"),
    (126, 0x7E, "MACHINE_PART", "Machine Part"),
    (127, 0x7F, "EGG_TICKET", "Egg Ticket"),
    (128, 0x80, "LOST_ITEM", "Lost Item"),
    (129, 0x81, "STARDUST", "Stardust"),
    (130, 0x82, "STAR_PIECE", "Star Piece"),
    (131, 0x83, "BASEMENT_KEY", "Basement Key"),
    (132, 0x84, "PASS", "Pass"),
    (133, 0x85, "ITEM_85", "Unused Item 85"),
    (134, 0x86, "ITEM_86", "Unused Item 86"),
    (135, 0x87, "ITEM_87", "Unused Item 87"),
    (136, 0x88, "CHARCOAL", "Charcoal"),
    (137, 0x89, "BERRY_JUICE", "Berry Juice"),
    (138, 0x8A, "SCOPE_LENS", "Scope Lens"),
    (139, 0x8B, "ITEM_8B", "Unused Item 8B"),
    (140, 0x8C, "ITEM_8C", "Unused Item 8C"),
    (141, 0x8D, "METAL_COAT", "Metal Coat"),
    (142, 0x8E, "DRAGON_FANG", "Dragon Fang"),
    (143, 0x8F, "ITEM_8F", "Unused Item 8F"),
    (144, 0x90, "LEFTOVERS", "Leftovers"),
    (145, 0x91, "ITEM_91", "Unused Item 91"),
    (146, 0x92, "ITEM_92", "Unused Item 92"),
    (147, 0x93, "ITEM_93", "Unused Item 93"),
    (148, 0x94, "MYSTERYBERRY", "Mysteryberry"),
    (149, 0x95, "DRAGON_SCALE", "Dragon Scale"),
    (150, 0x96, "BERSERK_GENE", "Berserk Gene"),
    (151, 0x97, "ITEM_97", "Unused Item 97"),
    (152, 0x98, "ITEM_98", "Unused Item 98"),
    (153, 0x99, "ITEM_99", "Unused Item 99"),
    (154, 0x9A, "SACRED_ASH", "Sacred Ash"),
    (155, 0x9B, "HEAVY_BALL", "Heavy Ball"),
    (156, 0x9C, "FLOWER_MAIL", "Flower Mail"),
    (157, 0x9D, "LEVEL_BALL", "Level Ball"),
    (158, 0x9E, "LURE_BALL", "Lure Ball"),
    (159, 0x9F, "FAST_BALL", "Fast Ball"),
    (160, 0xA0, "ITEM_A0", "Unused Item A0"),
    (161, 0xA1, "LIGHT_BALL", "Light Ball"),
    (162, 0xA2, "FRIEND_BALL", "Friend Ball"),
    (163, 0xA3, "MOON_BALL", "Moon Ball"),
    (164, 0xA4, "LOVE_BALL", "Love Ball"),
    (165, 0xA5, "NORMAL_BOX", "Normal Box"),
    (166, 0xA6, "GORGEOUS_BOX", "Gorgeous Box"),
    (167, 0xA7, "SUN_STONE", "Sun Stone"),
    (168, 0xA8, "POLKADOT_BOW", "Polkadot Bow"),
    (169, 0xA9, "ITEM_A9", "Unused Item A9"),
    (170, 0xAA, "UP_GRADE", "Up-Grade"),
    (171, 0xAB, "BERRY", "Berry"),
    (172, 0xAC, "GOLD_BERRY", "Gold Berry"),
    (173, 0xAD, "SQUIRTBOTTLE", "SquirtBottle"),
    (174, 0xAE, "ITEM_AE", "Unused Item AE"),
    (175, 0xAF, "PARK_BALL", "Park Ball"),
    (176, 0xB0, "RAINBOW_WING", "Rainbow Wing"),
    (177, 0xB1, "ITEM_B1", "Unused Item B1"),
    (178, 0xB2, "BRICK_PIECE", "Brick Piece"),
    (179, 0xB3, "SURF_MAIL", "Surf Mail"),
    (180, 0xB4, "LITEBLUEMAIL", "Liteblue Mail"),
    (181, 0xB5, "PORTRAITMAIL", "Portrait Mail"),
    (182, 0xB6, "LOVELY_MAIL", "Lovely Mail"),
    (183, 0xB7, "EON_MAIL", "Eon Mail"),
    (184, 0xB8, "MORPH_MAIL", "Morph Mail"),
    (185, 0xB9, "BLUESKY_MAIL", "Bluesky Mail"),
    (186, 0xBA, "MUSIC_MAIL", "Music Mail"),
    (187, 0xBB, "MIRAGE_MAIL", "Mirage Mail"),
]

code_lines = [
    '#!/usr/bin/env python3',
    '"""',
    'General Item Finder Tool for Gen 2 Recomped (Silver / Gold / Crystal).',
    '"""',
    '',
    'import sys',
    '',
    'GEN2_RECOMP_ITEMS = ['
]

for dec, hex_val, key, name in pokesilver_items:
    code_lines.append(f'    ({dec}, 0x{hex_val:02X}, "{key}", "{name}"),')

code_lines.extend([
    ']',
    '',
    'def search_item(query):',
    '    query = query.strip()',
    '    if not query:',
    '        return',
    '',
    '    cleaned = query.upper().replace("ITEM_", "")',
    '    matches = []',
    '    val = None',
    '    if query.startswith("0x") or query.startswith("0X"):',
    '        try:',
    '            val = int(query, 16)',
    '        except ValueError:',
    '            pass',
    '    elif cleaned.isdigit():',
    '        try:',
    '            val = int(cleaned, 10)',
    '        except ValueError:',
    '            pass',
    '',
    '    hex_val_direct = None',
    '    if len(query.strip()) == 2:',
    '        try:',
    '            hex_val_direct = int(query.strip(), 16)',
    '        except ValueError:',
    '            pass',
    '',
    '    for dec, hex_val, key, name in GEN2_RECOMP_ITEMS:',
    '        if (val is not None and (dec == val or hex_val == val)) or \\',
    '           (hex_val_direct is not None and hex_val == hex_val_direct):',
    '            matches.append((dec, hex_val, key, name))',
    '            continue',
    '            ',
    '        if query.lower() in name.lower() or query.upper() in key.upper():',
    '            matches.append((dec, hex_val, key, name))',
    '',
    '    if not matches:',
    '        print(f"❌ No matching item found for query: \'{query}\'")',
    '        return',
    '',
    '    print(f"\\nFound {len(matches)} matching item(s):\\n")',
    '    print(f"{\'Recomp ID\':<12} | {\'Hex Byte\':<10} | {\'Item Name\'}")',
    '    print("-" * 48)',
    '    for dec, hex_val, key, name in matches:',
    '        print(f"ITEM_{dec:03d}     | 0x{hex_val:02X} (Hex) | {name}")',
    '    print()',
    '',
    'def main():',
    '    if len(sys.argv) > 1:',
    '        query = " ".join(sys.argv[1:])',
    '        search_item(query)',
    '    else:',
    '        print("=== Gen 2 Recomp Item Finder ===")',
    '        print("Type an item name (e.g. \'nevermeltice\'), Hex byte (e.g. \'0x69\'), or Recomp ID (e.g. \'105\').")',
    '        print("Type \'exit\' or \'q\' to quit.\\n")',
    '        while True:',
    '            try:',
    '                user_input = input("Search item > ")',
    '                if user_input.strip().lower() in ("exit", "quit", "q"):',
    '                    break',
    '                search_item(user_input)',
    '            except (KeyboardInterrupt, EOFError):',
    '                print("\\nGoodbye!")',
    '                break',
    '',
    'if __name__ == "__main__":',
    '    main()',
])

with open("item_finder.py", "w", encoding="utf-8") as f:
    f.write("\n".join(code_lines))

print("Created item_finder.py with Silver / Gold ROM item order!")
